# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 0a87040e0877af3eb235413a0cfa37cdeea8a845e5fdb2dfe0e58e296bdb6f1091f10cee81e9873118b5003c1721884236d564b6c3d990ef656bdd3545a6badf

test:
  secret_key_base: 3bd1b7537d19bf1fed7a6c626734d3c1c1049a83c3731576b2326e5457c0b5553d25e87d32f1f541a9f5b901235aca12de414e94e766cebae938d1574e193820

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
